config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('materials/', include('materials.urls', namespace='materials')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.apps import MainConfig
from main.views import contact, StudentListView, StudentDetailView, StudentCreateView, StudentUpdateView, \
    StudentDeleteView, toggle_activity

app_name = MainConfig.name


urlpatterns = [
    path('', StudentListView.as_view(), name='index'),
    path('view/<int:pk>/', StudentDetailView.as_view(), name='view_student'),
    path('contact/', contact, name='contact'),
    path('create/', StudentCreateView.as_view(), name='create_student'),
    path('edit/<int:pk>/', StudentUpdateView.as_view(), name='update_student'),
    path('delete/<int:pk>/', StudentDeleteView.as_view(), name='delete_student'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

main/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Students(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    avatar = models.ImageField(upload_to='students/', verbose_name='аватар', **NULLABLE)

    is_active = models.BooleanField(default=True, verbose_name='online')

    email = models.CharField(max_length=150, verbose_name='email', unique=True, **NULLABLE)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'студент'
        verbose_name_plural = 'студенты'
        ordering = ('last_name',)


class Subject(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, verbose_name='студент')
    title = models.CharField(max_length=150, verbose_name='название')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'предмет'
        verbose_name_plural = 'предметы'
        ordering = ('title',)

main/forms.py
from django import forms

from main.models import Students, Subject


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class StudentForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Students
        fields = ('first_name', 'last_name', 'avatar', 'email',)
        # exclude = ('is_active')

    def clean_email(self):
        cleaned_data = self.cleaned_data['email']

        if 'sky.pro' not in cleaned_data:
            raise forms.ValidationError('Почта должна относиться к учебному заведению')

        return cleaned_data

class SubjectForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Subject
        fields = '__all__'

main/views.py
from django.conf import settings
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from main.forms import StudentForm, SubjectForm
from main.models import Students, Subject


class StudentListView(ListView):
    model = Students


class StudentDetailView(DetailView):
    model = Students
    template_name = 'main/students_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if settings.CACHE_ENABLED:
            key = f'subject_list_{self.object.pk}'
            subject_list = cache.get(key)
            if subject_list is None:
                subject_list = self.object.subject_set.all()
                cache.set(key, subject_list)
        else:
            subject_list = self.object.subject_set.all()

        context['subjects'] = subject_list
        return context


class StudentCreateView(CreateView):
    model = Students
    form_class = StudentForm
    success_url = reverse_lazy('main:index')


class StudentUpdateView(UpdateView):
    model = Students
    form_class = StudentForm

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def get_success_url(self):
        return reverse('main:update_student', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Students, Subject, form=SubjectForm, extra=1)
        if self.request.method == "POST":
            formset = SubjectFormset(self.request.POST, instance=self.object)
        else:
            formset = SubjectFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class StudentDeleteView(DeleteView):
    model = Students
    success_url = reverse_lazy('main:index')


def toggle_activity(request, pk):
    student_item = get_object_or_404(Students, pk=pk)
    if student_item.is_active:
        student_item.is_active = False
    else:
        student_item.is_active = True

    student_item.save()

    return redirect(reverse('main:index'))

def contact(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f'{name} {email} {message}')

    context = {
        'title': 'Контакты'
    }
    return render(request, 'main/contact.html', context)

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">Какая-то информация</h4>
                    <p class="text-muted">какое-то описание.</p>
                </div>
                {% include 'main/includes/inc_main_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Album</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% block contents %}
                {% endblock %}
            </div>

        </div>
    </div>
</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p> &copy; {% now 'Y' %}</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% block contents %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                Офис МСК<br>
                Офис СПБ
            </p>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <H2>Написать</H2>
            {% csrf_token %}
            <input class="form-control mb-2" name="name">
            <input class="form-control mb-2" name="email">
            <textarea class="form-control mb-2" name="message"></textarea>
            <button type="submit" class="btn btn-primary form-control">Submit</button>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/students_confirm_delete.html
{% extends 'main/base.html' %}

{% block contents %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить '{{ object.first_name }} {{ object.last_name }}' ?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'main:index' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/students_detail.html
{% extends 'main/base.html' %}

{% block contents %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация студента
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Почта</th>
                        </tr>
                        <tr>
                            <td>{{ object.first_name }}</td>
                            <td>{{object.last_name}}</td>
                              <td>{{ object.email }}</td>
                        </tr>
                    </table>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">
                        Предмет
                    </h2>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <th>Название</th>
                            <th>Описание</th>
                        </tr>
                        {% for subject in subjects %}
                        <tr>
                            <td>{{ subject.title }}</td>
                            <td>{{ subject.description }}</td>
                        </tr>
                         {% endfor %}
                    </table>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/students_form.html
{% extends 'main/base.html' %}

{% block contents %}
<form class="col-12" method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">
                        Добавление студента
                    </h2>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">
                        Добавление предмета
                    </h2>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

main/templates/main/students_list.html
{% extends 'main/base.html' %}
{% block contents %}
<div class="col-12 mb-4">
    <a class="btn btn-outline success" href=" {% url 'main:create_student' %} ">Добавить студента</a>
</div>
{% for object in object_list %}
<div class="col-mb-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {% if object.is_active %}
                    {{object | title}}
                {% else %}
                    <span class="text-muted">{{ object.title }}</span>
                {% endif %}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'main:view_student' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">View</a>
                    <a href="{% url 'main:update_student' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Edit</a>
                    <a href="{% url 'main:delete_student' object.pk%}" type="button"
                       class="btn btn-sm btn-outline-danger">Delete</a>
                </div>
                {% if object.is_active  %}
                    <a class="btn btn-warning" href="{% url 'main:toggle_activity' object.pk %}">Деактевировать</a>
                {% else %}
                    <a class="btn btn-success" href="{% url 'main:toggle_activity' object.pk %}">Актевировать</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

main/templates/main/students_view.html
{% extends 'main/base.html' %}

{% block contents %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">
                        Информация студента
                    </h2>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Имя</td>
                            <td>{{ object.first_name }}</td>
                        </tr>
                        <tr>
                            <td>Фамилия</td>
                            <td>{{ object.last_name }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}